package entity;
// Generated Oct 23, 2016 10:43:49 PM by Hibernate Tools 4.3.1



/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private String code;
     private String name;
     private Float price;

    public Products() {
    }

	
    public Products(String code) {
        this.code = code;
    }
    public Products(String code, String name, Float price) {
       this.code = code;
       this.name = name;
       this.price = price;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }




}


